name: CI - Docker Build & Push

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'backend/history-services/GIT_SHA.txt'

jobs:
  # ======================
  # History Service
  # ======================
  history-service:
    runs-on: self-hosted
    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      GIT_SHA: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Linting (Flake8)
        run: pip install flake8 && flake8 backend/history-services || true
        continue-on-error: true

      - name: SAST (CodeQL Analysis)
        uses: github/codeql-action/analyze@v2
        continue-on-error: true

      - name: SCA (Safety)
        run: pip install safety && safety check -r backend/history-services/requirements.txt || true
        continue-on-error: true

      - name: Unit Tests (pytest)
        run: pip install pytest && pytest backend/history-services/tests || true
        continue-on-error: true

      - name: DAST (OWASP ZAP Baseline Scan)
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'http://localhost:5000'
        continue-on-error: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build & Push History Service
        run: |
          cd backend/history-services
          docker build -t ${{ env.DOCKER_HUB_USERNAME }}/history-service:${{ env.GIT_SHA }} .
          docker push ${{ env.DOCKER_HUB_USERNAME }}/history-service:${{ env.GIT_SHA }}

      - name: Save Git SHA to file
        run: |
          echo "${{ env.GIT_SHA }}" > backend/history-services/GIT_SHA.txt

      - name: Commit SHA file
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add backend/history-services/GIT_SHA.txt
          git commit -m "Update latest Git SHA" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}

      - name: Image Scan (Trivy - History Service)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.DOCKER_HUB_USERNAME }}/history-service:${{ env.GIT_SHA }}
          format: table
          exit-code: 0
        continue-on-error: true
